- name: Configuration de la timezone
  hosts: all

  tasks:
    - name: Set timezone variables
      copy: content="Etc/UTC\n"
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone
    
    - name: Reconfigure Timezone Data
      shell: timedatectl set-timezone Europe/Paris
      sudo: true
      when: timezone.changed
