- name: Installation et configuration server NFS
  hosts: all
  vars:
   - packages:
     - nfs-common
     - nfs-kernel-server
  tasks:
    - name: Create dossier /srv/nfs/kubedata
      file: path=/srv/nfs/kubedata state=directory mode=777 owner=root group=root
    
    - name: Installation des packages nfs-common et nfs-kernel-server
       apt:
         pkg: "{{ packages }}"
         state: latest
         update_cache: yes

    - name: Copie du fichier /etc/exports
      template: src=templates/exports.j2 dest=/etc/exports owner=root group=root

    - name: restart nfs server
      service: name=nfs-kernel-server state=restarted

    - name: Update apt package
      apt:
      name: "*"
      state: latest
      update_cache: yes
      - name: Install Packages
        apt:
          pkg: "{{ packages }}"
          state: latest
          update_cache: yes
