- name: Installation et configuration server NFS
  hosts: all
  tasks:
    - name: Create dossier /srv/nfs/kubedata
      file: path=/srv/nfs/kubedata state=directory mode=777 owner=root group=roo
    
    - name: Verification presence package nfs-common et nfs-kernel-server
      apt: name={{ item }} state=installed update_cache=yes
      with_items:
        - nfs-common
        - nfs-kernel-server

    - name: Copie du fichier /etc/exports
      template: src=templates/exports.j2 dest=/etc/exports owner=root group=root

    - name: restart nfs server
      service: name=nfs-kernel-server state=restarted

